export enum PageCodes {
    PAGE_MAIN = 'PAGE_MAIN',
    PAGE_AIRTEL = 'PAGE_AIRTEL',
    PAGE_FLIGHT = 'PAGE_FLIGHT',
    PAGE_HOTEL = 'PAGE_HOTEL',
    PAGE_CAR = 'PAGE_CAR',
    PAGE_RENT = 'PAGE_RENT',
    PAGE_ACTIVITY = 'PAGE_ACTIVITY',
    PAGE_MEMBER = 'PAGE_MEMBER',
    PAGE_MY = 'PAGE_MY',
}
